fps: 60

window:
  width: 1280
  height: 720
  title: HORIZON
  bg_rgb: [14, 15, 18]

ui:
  textbox:
    width_frac: 0.35    # width = 30% of window
    height_frac: 0.8   # height = 80% of window

input:
  scroll_wheel_pixels: 40
  page_scroll_frac: 0.9